!***********************************************************************************************************************************
!*                                       S U B R O U T I N E    R E S T A R T   O U T P U T                                       **
!***********************************************************************************************************************************

SUBROUTINE RESTART_OUTPUT (RSOFN)
  USE GLOBAL; USE SCREENC; USE RSTART; USE GDAYC; USE GEOMC; USE KINETIC, ONLY:EPM,EPD,SEDC,SEDN,SEDP, SDKV; USE TVDC, ONLY:QSUM     
  USE KINETIC, ONLY:SED, PFLUXIN,NFLUXIN ; USE EDDY, ONLY: TKE; USE MAIN, ONLY:WARNING_OPEN,NXWL,NXFLOWBAL,NXNPBAL; USE LOGICC;USE STRUCTURES
  ! MACROPHYTEC removed
  IMPLICIT NONE
  
  CHARACTER(*) :: RSOFN
  OPEN  (RSO,FILE=RSOFN,FORM='UNFORMATTED',STATUS='UNKNOWN')
  WRITE (RSO) NIT,    NV,     KMIN,   IMIN,   NSPRF,  CMBRT,  ZMIN,   IZMIN,  START,  CURRENT
  WRITE (RSO) DLTDP,  SNPDP,  TSRDP,  VPLDP,  PRFDP,  CPLDP,  SPRDP,  RSODP,  SCRDP,  FLXDP,  WDODP
  WRITE (RSO) JDAY,    ELTM,   ELTMF,  DLT,    DLTAV,  DLTS,   MINDLT, JDMIN,  CURMAX
  WRITE (RSO) NXTMSN, NXTMTS, NXTMPR, NXTMCP, NXTMVP, NXTMRS, NXTMSC, NXTMSP, NXTMFL, NXTMWD, NXWL, NXFLOWBAL, NXNPBAL,NXTMWD_SEC, NXTMUK
  WRITE (RSO) VOLIN,  VOLOUT, VOLUH,  VOLDH,  VOLPR,  VOLTRB, VOLDT,  VOLWD,  VOLEV,  VOLSBR, VOLTR, VOLSR,VOLICE,ICEBANK
  WRITE (RSO) TSSEV,  TSSPR,  TSSTR,  TSSDT,  TSSWD,  TSSIN,  TSSOUT, TSSS,   TSSB,   TSSICE
  WRITE (RSO) TSSUH,  TSSDH,  TSSUH2, TSSDH2, CSSUH2, CSSDH2, VOLUH2, VOLDH2, QUH1
  WRITE (RSO) ESBR,   ETBR,   EBRI
  WRITE (RSO) Z,      SZ,     ELWS,   SAVH2,  SAVHR,  H2
  WRITE (RSO) KTWB,   KTI,    SKTI,   SBKT
  WRITE (RSO) ICE,    ICETH,  CUF,    QSUM
  WRITE (RSO) U,      W,      SU,     SW,     AZ,     SAZ,    DLTLIM, SELWS
  WRITE (RSO) T1,     T2,     C1,     C2,     C1S,    SED,    KFS,    CSSK
  WRITE (RSO) EPD,   EPM
#ifdef MACROPHYTEC
  WRITE (RSO) MACMBRT,MACRC, MAC, MACRM,  MACSS
#endif
  WRITE (RSO) SEDC, SEDN, SEDP, CD  ! mlm 10/06  ! ZOO removed 2026-03-30
  WRITE(RSO) SDKV                        ! MLM 6/10/07
  WRITE(RSO) TKE                         ! SW 10/4/07
  WRITE(RSO) BR_INACTIVE,WARNING_OPEN   ! SW 8/1/2018
  ! ENVIRPMOD removed 2026-03-30
  IF(PIPES)WRITE(RSO)YS,VS,VST,YST,DTP,QOLD
  WRITE(RSO)TPOUT,TPTRIB,TPDTRIB,TPWD,TPPR,TPIN,TP_SEDSOD_PO4,PFLUXIN,TNOUT,TNTRIB,TNDTRIB,TNWD,TNPR,TNIN,TN_SEDSOD_NH4,NFLUXIN,ATMDEP_P,ATMDEP_N,NH3GASLOSS    !TP_SEDBURIAL,TN_SEDBURIAL,

  CLOSE (RSO)
END SUBROUTINE RESTART_OUTPUT